# https://taskfile.dev

version: '3'

tasks:
  netbox:
    desc: Update the sha version of the netbox library
    cmds:
      - go get github.com/rsapc/netbox@{{.CLI_ARGS}}
  run:
    desc: Run from source using the .env environment
    dotenv: [ .env ]
    cmds:
      -  go run main.go

  build:
    desc: Build the linux binary
    env: 
      GOOS: linux
    cmds:
      - go build


